cheese = Ingredient.create(name:'du fromage')
bread = Ingredient.create(name:'du pain')
ham = Ingredient.create(name:'le jambon')
chicken = Ingredient.create(name:'du poulet')
strawberries = Ingredient.create(name:'les fraises')
eggs = Ingredient.create(name:'les oeuvres')
spinach = Ingredient.create(name:'des epinards')

j = User.create(name: 'Joan of Arc')
ni = User.create(name: 'Nichola')
v = User.create(name: 'Violette')
na = User.create(name: 'Napolean')

jAllergen = Allergen.create(name:'gluten', user:j, ingredient:bread)
niAllergen = Allergen.create(name:'gluten', user:ni, ingredient:bread)
vAllergen = Allergen.create(name:'lactose', user:v, ingredient:cheese)
naAllergen = Allergen.create(name:'defeat', user:na, ingredient:chicken)

c = Recipe.create(name: 'Une Croque Madame', user: j)
f = Recipe.create(name: 'L\'Omlette Du Fromage', user: na)
po = Recipe.create(name: 'L\'Omlette Avec Du Poulet', user: ni)
e = Recipe.create(name: 'Quiche Des Epinards Avec Les Fraises', user: v)

RecipeIngredient.create(recipe:c, ingredient:eggs)
RecipeIngredient.create(recipe:f, ingredient:eggs)
RecipeIngredient.create(recipe:po, ingredient:eggs)
RecipeIngredient.create(recipe:e, ingredient:eggs)
RecipeIngredient.create(recipe:e, ingredient:spinach)
RecipeIngredient.create(recipe:po, ingredient:chicken)
RecipeIngredient.create(recipe:c, ingredient:bread)
RecipeIngredient.create(recipe:f, ingredient:cheese)
RecipeIngredient.create(recipe:e, ingredient:strawberries)